#pragma once

#include "ap_version.h"

#define THISFIRMWARE "TJW:Copter_BRIDGE_HEX v0.1-beta"
#define FIRMWARE_VERSION 3,4,2,FIRMWARE_VERSION_TYPE_OFFICIAL

#ifndef GIT_VERSION
#define FIRMWARE_STRING THISFIRMWARE
#else
#define FIRMWARE_STRING THISFIRMWARE " (" GIT_VERSION ")"
#endif
